version: "3.9"

services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./dump_db.sql:/docker-entrypoint-initdb.d/dummy_dump.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=room_reservations
  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=room_reservations
    depends_on:
      - db
    restart: on-failure
